export const storeData = [
  {
    restaurant_id: 1,
    name: "McDonalds",
    contact_info: "512-3341",
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqHutQ-GEKZlgbk4wwnLbEVkbTlrVOWugesg&s",
    banner_url:
      "https://d3.harvard.edu/platform-digit/wp-content/uploads/sites/2/2018/04/brandbanner-mcd-1100x200.png",
    address_id: 1,
    created_at: "2024-06-02T12:30:00Z",
    cuisine: "Burgers",
    price_range: "₱₱",
    rating: 4.8,
    reviews: 3250,
    delivery_time: "15-25 min",
    delivery_fee: "₱39",
    distance: "1.2 km",
    promo_tag: "Free delivery",
  },
  {
    restaurant_id: 2,
    name: "Jollibee",
    contact_info: "512-3341",
    image_url:
      "https://upload.wikimedia.org/wikipedia/en/thumb/8/84/Jollibee_2011_logo.svg/500px-Jollibee_2011_logo.svg.png",
    banner_url:
      "https://assets3.thrillist.com/v1/image/2809418/1200x630/flatten;crop_down;webp=auto;jpeg_quality=70",
    address_id: 3,
    created_at: "2024-06-02T12:30:00Z",
    cuisine: "Fast Food",
    price_range: "₱₱",
    rating: 4.9,
    reviews: 4100,
    delivery_time: "15-30 min",
    delivery_fee: "₱29",
    distance: "1.0 km",
    promo_tag: "₱50 off",
  },
  {
    restaurant_id: 3,
    name: "KFC",
    contact_info: "533-2290",
    image_url:
      "https://upload.wikimedia.org/wikipedia/en/thumb/5/57/KFC_logo-image.svg/250px-KFC_logo-image.svg.png",
    banner_url:
      "https://pimwp.s3-accelerate.amazonaws.com/2021/12/Screenshot-2021-12-28-132323.jpg",
    address_id: 2,
    created_at: "2024-06-03T10:15:00Z",
    cuisine: "Fried Chicken",
    price_range: "₱₱",
    rating: 4.7,
    reviews: 2800,
    delivery_time: "20-35 min",
    delivery_fee: "₱49",
    distance: "1.8 km",
    promo_tag: "Free drink",
  },
  {
    restaurant_id: 4,
    name: "Mang Inasal",
    contact_info: "545-8892",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Mang_Inasal.svg",
    banner_url:
      "https://gadaboutprincess.com/wp-content/uploads/2022/09/Ihaw-Sarap-Banner-1920x1008.jpg",
    address_id: 4,
    created_at: "2024-06-04T09:45:00Z",
    cuisine: "Filipino",
    price_range: "₱₱",
    rating: 4.8,
    reviews: 2100,
    delivery_time: "20-30 min",
    delivery_fee: "₱35",
    distance: "1.5 km",
    promo_tag: "Sulit meals",
  },
  {
    restaurant_id: 5,
    name: "Chowking",
    contact_info: "578-1123",
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0ybcmWVPS0MpvWDjS3mdT0KuDIsBHvmq_IA&s",
    banner_url:
      "https://www.chowking.ph/wp-content/uploads/2023/11/Share-Image.png?q=80&w=1200&h=630",
    address_id: 5,
    created_at: "2024-06-05T14:20:00Z",
    cuisine: "Chinese",
    price_range: "₱₱",
    rating: 4.6,
    reviews: 1900,
    delivery_time: "20-35 min",
    delivery_fee: "₱45",
    distance: "2.0 km",
    promo_tag: "Free delivery",
  },
  {
    restaurant_id: 6,
    name: "Greenwich",
    contact_info: "590-4432",
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzQ-yc85xJoNMktdIloK4hK_EShvAv3OVi9g&s",
    banner_url:
      "https://www.facebook.com/photo/?fbid=1289712639854953&set=a.653852580107632",
    address_id: 6,
    created_at: "2024-06-06T11:10:00Z",
    cuisine: "Pizza",
    price_range: "₱₱",
    rating: 4.7,
    reviews: 2300,
    delivery_time: "20-30 min",
    delivery_fee: "₱39",
    distance: "1.7 km",
    promo_tag: "Barkada deal",
  },
  {
    restaurant_id: 7,
    name: "Pizza Hut",
    contact_info: "601-7788",
    image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Pizza_hut_logo_international.svg/960px-Pizza_hut_logo_international.svg.png",
    banner_url:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Pizza_Hut_(SM_City_BF_Parañaque_branch)_storefront.jpg?width=1600",
    address_id: 7,
    created_at: "2024-06-07T16:25:00Z",
    cuisine: "Pizza",
    price_range: "₱₱",
    rating: 4.8,
    reviews: 1750,
    delivery_time: "20-35 min",
    delivery_fee: "₱49",
    distance: "2.3 km",
    promo_tag: "Buy 1 Take 1",
  },
  {
    restaurant_id: 8,
    name: "Burger King",
    contact_info: "612-9901",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Burger_King_2020.svg",
    banner_url:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Burger_King_Festival_Supermall_exterior.jpg?width=1600",
    address_id: 8,
    created_at: "2024-06-08T13:50:00Z",
    cuisine: "Burgers",
    price_range: "₱₱",
    rating: 4.7,
    reviews: 1600,
    delivery_time: "20-30 min",
    delivery_fee: "₱35",
    distance: "1.9 km",
    promo_tag: "Whopper deal",
  },
  {
    restaurant_id: 9,
    name: "Army Navy",
    contact_info: "623-4455",
    image_url:
      "https://static.wikia.nocookie.net/logopedia/images/a/a6/ArmyNavy_2009_stacked.png/revision/latest/scale-to-width-down/1200?cb=20240224064642",
    banner_url:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Jf7639Army_Navy_Burger_Burritofvf_02.JPG?width=1600",
    address_id: 9,
    created_at: "2024-06-09T08:30:00Z",
    cuisine: "Burgers",
    price_range: "₱₱",
    rating: 4.5,
    reviews: 980,
    delivery_time: "25-40 min",
    delivery_fee: "₱55",
    distance: "3.1 km",
    promo_tag: "Combo meals",
  },
  {
    restaurant_id: 10,
    name: "Shakey's",
    contact_info: "634-2233",
    image_url:
      "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Shakey%27s_US_logo.svg/1280px-Shakey%27s_US_logo.svg.png",
    banner_url:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Shakey%27s_Festival_Supermall_storefront.jpg?width=1600",
    address_id: 10,
    created_at: "2024-06-10T18:00:00Z",
    cuisine: "Pizza",
    price_range: "₱₱",
    rating: 4.6,
    reviews: 1420,
    delivery_time: "20-35 min",
    delivery_fee: "₱45",
    distance: "2.6 km",
    promo_tag: "Family bundle",
  },
  {
    restaurant_id: 11,
    name: "Domino's Pizza",
    contact_info: "655-3321",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/7/74/Dominos_pizza_logo.svg",
    banner_url:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Domino%27s_Pizza,_SM_Hypermarket_Sucat_Lopez.jpg?width=1600",
    address_id: 11,
    created_at: "2024-06-11T10:00:00Z",
    cuisine: "Pizza",
    price_range: "₱₱",
    rating: 4.7,
    reviews: 1680,
    delivery_time: "20-30 min",
    delivery_fee: "₱39",
    distance: "2.1 km",
    promo_tag: "Free delivery",
  },
  {
    restaurant_id: 12,
    name: "Starbucks",
    contact_info: "677-8890",
    image_url:
      "https://upload.wikimedia.org/wikipedia/sco/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/3840px-Starbucks_Corporation_Logo_2011.svg.png",
    banner_url:
      "https://www.premieroutlet.hu/fileadmin/user_upload/starbucks_banner.png",
    address_id: 12,
    created_at: "2024-06-12T09:00:00Z",
    cuisine: "Coffee",
    price_range: "₱₱₱",
    rating: 4.9,
    reviews: 2500,
    delivery_time: "15-25 min",
    delivery_fee: "₱29",
    distance: "1.1 km",
    promo_tag: "Free pastry",
  },
];